# Generated by Django 3.2.18 on 2023-07-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='delivered',
            field=models.IntegerField(default=0, verbose_name='Доставлено'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='rejection',
            field=models.IntegerField(default=0, verbose_name='Отказ'),
        ),
    ]
