# Generated by Django 3.2.18 on 2023-07-06 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_auto_20230707_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='wight',
            new_name='weight',
        ),
    ]
