# Generated by Django 3.2.18 on 2023-07-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_rename_wight_package_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='weight',
            field=models.FloatField(verbose_name='Вес'),
        ),
    ]
