# Generated by Django 3.2.18 on 2023-07-06 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnersType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('code', models.IntegerField(verbose_name='Код типа партнера')),
            ],
            options={
                'verbose_name': 'Тип партнера',
                'verbose_name_plural': 'Типы партнеров',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('token', models.CharField(max_length=50, verbose_name='Токен')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partnerstype', verbose_name='Тип контрагента')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
    ]
